### ISSUE TITLE
Hey bro, 

### ISSUE THREAD

**Issue by ETSDriver1** [StOneRPC/ETS2Trainer#1]
Could you quickly explain how I can update this? I've got it to inject but it just crashes upon hook inject.  Do I need to update "Memory::FindDMAAddy(moduleBase + 0x0160ABA0",  I've got my recent working offset's for the stuff I need, just need a little help to get started, if you don't mind.

**Comment by SloanPC** [comment]
Hey, It's been a while since I've updated this trainer so I would imagine more than just the base offset has changed. You will probably need to use reclass.net to update the structs in ETS2.h and then update the base address. If I have time either later today or some point this week then I'll see if I can push an update for the latest ETS2 version 🙂
